
# This file was *autogenerated* from the file rsa.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_8 = Integer(8)
from random import getrandbits, randint
from array import array
from sage.crypto.util import bin_to_ascii
from sage.crypto.util import ascii_to_bin


class RSA(object):

    def __init__(self, object=None):
        self.message = object
        self.m = []
        self.n = _sage_const_0 
        self.blocks = []
        self.e = _sage_const_0 
        self.d = _sage_const_0 
        self.encryption_message = []
        self.decryption_message = ""

    def session_key(self, block_bits):
        binary = ascii_to_bin(self.message)
        binary = str(binary)
        self.m = [int(binary[i:i+block_bits], _sage_const_2 )
                  for i in range(_sage_const_0 , len(binary), block_bits)]

    @staticmethod
    def gen_primary_number(bits, p=_sage_const_0 ):
        p = getrandbits(bits)
        while p not in Primes():
            p = getrandbits(bits)
        return p

    def __ColculationPublicExponent(self, Fi):
        self.e = randint(_sage_const_2 , Fi-_sage_const_1 )
        while gcd(self.e, Fi) != _sage_const_1 :
            self.e = randint(_sage_const_2 , Fi)

    def __ColculationSecretExponent(self, Fi):
        self.d = inverse_mod(self.e, Fi)

    def encrypt(self):
        R = IntegerModRing(self.n)
        self.encryption_message = [R(x)**R(self.e) for x in self.m]
        string = ""
        for x in self.encryption_message:
            string += str(x)
        with open("encrypt.txt", "w") as text_file:
            text_file.write("{0}\n".format(string))

    def decrypt(self):
        R = IntegerModRing(self.n)
        dec_blocks = [str(R(x)**R(self.d)) for x in self.encryption_message]
        dec_blocks = [bin(int(block))[_sage_const_2 :] for block in dec_blocks]
        for i in range(len(dec_blocks)):
            if len(dec_blocks[i]) % _sage_const_8 :
                block = (_sage_const_8 -(len(dec_blocks[i]) % _sage_const_8 ))*"0"+dec_blocks[i]
                dec_blocks.pop(i)
                dec_blocks.insert(i, block)
        dec_msg = [bin_to_ascii(x) for x in dec_blocks]
        for x in dec_msg:
            self.decryption_message += x
        with open("decrypt.txt", "w") as text_file:
            text_file.write("{0}\n".format(self.decryption_message))

    def run(self):
        try:
            bits = int(raw_input(
                       "Please input number of bits for primary numbers: "))
            block_bits = int(raw_input(
                        "Please input number of bits in block: "))
        except:
            print "KOGO NAEBAT` XOCHESH?"
            return
        self.session_key(block_bits)
        p = RSA.gen_primary_number(bits)
        q = RSA.gen_primary_number(bits)
        print "p: %s " % p
        print "q: %s" % q
        self.n = p*q
        Fi = (p-_sage_const_1 )*(q-_sage_const_1 )
        self.__ColculationPublicExponent(Fi)
        self.__ColculationSecretExponent(Fi)
        if mod(self.e*self.d, Fi) != _sage_const_1 :
            print "Bad calculations :("
            return
        self.encrypt()
        self.decrypt()
        if self.message == self.decryption_message:
            print "All right!"


def main():
    with open('plaintext.txt', 'r') as myfile:
        data = myfile.read().replace('\n', '')
    rsa = RSA(data)
    rsa.run()


if __name__ == "__main__":
    main()

